name: Cultivation
author: Sefiraat, J3fftw, JustAHuman
description: A Spiritual Successor to ExoticGarden
main: dev.sefiraat.cultivation.Cultivation
website: https://github.com/Sefiraat/Cultivation
version: ${project.version}
api-version: 1.19
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
commands:
  cultivation:
    description: /cultivation
    usage: /cultivation <sub>
permissions:
  cultivation.*:
    description: Provides permissions for all Cultivation functions
    default: op
    children:
      cultivation.admin: true